platform :ios, '10.0'

target 'ShoppingApp' do
  use_frameworks!

  # Pods for ShoppingApp
  pod 'Alamofire'
  pod 'SwiftyJSON'

  target 'ShoppingAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
